example.property= I AM THE DEFAULT

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: root
    password: frad123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
